source 'https://rubygems.org'

gem 'cucumber'
gem 'capybara'
gem 'selenium-webdriver'
gem 'chromedriver-helper', '1.0.0'
gem 'rspec'
gem 'activesupport'
gem 'require_all'
gem 'rake'
gem 'poltergeist'
gem 'activerecord'
gem 'rspec-rails'
gem 'rails'